version: '3'
services:
    pytorch:
        image: mastering_pytorch_env:latest
        container_name: mastering_pytorch_jupyter_notebook
        tty: true
        stdin_open: true
        ports:
            - 8888:8888
        volumes:
            - ./:/workspace
            - /mnt/e:/workspace/dataset
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          capabilities: [gpu]
        command: jupyter notebook --allow-root --ip=0.0.0.0